config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :notifications, only: [:index]
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  post 'contacts/new' => 'contacts#new'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:edit, :update, :destroy, :show]
  before_action :permit_user, only: [:destroy, :update]

  def index
    @blogs = Blog.all.order(updated_at: :desc)
  end

  # showアクションを定義します。入力フォームと一覧を表示するためインスタンスを２つ生成します。
  def show
    @comment = @blog.comments.build
    @comments = @blog.comments
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id = current_user.id
    if @blog.save
      flash[:success] = "ブログを作成しました！"
      redirect_to blogs_path
      NoticeMailer.sendmail_blog(@blog).deliver
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    @blog.update(blogs_params)
    if @blog.invalid?
      render action: 'edit'
    else
      flash[:success] = "ブログを更新しました！"
      redirect_to blogs_path
    end
  end

  def destroy
    @blog.destroy
    flash[:success] = "ブログを削除しました！"
    redirect_to blogs_path
  end

  def confirm
    @blog = Blog.new(blogs_params)
    render 'new' if @blog.invalid?
  end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def permit_user
      redirect_to blogs_path unless current_user.id == @blog.user.id || current_user.admin?
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
    <%= f.error_messages! %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content, size: "50x5", class: 'form-control'  %>
    <br>
    <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/blogs/confirm.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h3>以下の内容で、送信します。</h3>
        <%= form_for(@blog) do |f| %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :content %>
            <p>タイトル:<%= @blog.title %></p>
            <p>本文:<%= @blog.content %></p>
            <%= f.submit "登録", class: 'btn btn-primary btn-block' %>
        <% end %>
        <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :content %>
            <%= f.submit "もどる", name: 'back', class: 'btn btn-primary btn-block' %>
        <% end %>
    </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>ブログを編集する</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
        <h1>ブログ一覧</h1>
        <%= link_to 'ブログを作成する', new_blog_path, class: 'btn btn-default' %>
        <% @blogs.each do |blog| %>
            <div class="row">
                <div class="blog-avatar">
                    <%= profile_img(blog.user) if profile_img(blog.user) %>
                </div>
                <h4><strong><%= link_to "#{blog.title}", blog_path(blog) %></strong></h4>
                <p><%= simple_format(blog.content) %></p>
                <div class="blog_user_name">投稿者: <%= link_to "#{blog.user.name}", user_path(blog.user) %></div>
                <div class="blog_user_name">投稿日: <%= localize(blog.created_at, format: :default) %></div>
                <% if blog.created_at < blog.updated_at %>
                    <div class="blog_user_name">(最終更新日: <%= localize(blog.updated_at, format: :default) %>)</div>
                <% end %>
                <% if current_user.id == blog.user.id || current_user.admin? %>
                    <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-success' %>
                    <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当によろしいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
                <% end %>
            </div>
        <% end %>
        <%= link_to "もどる", :back, class: 'btn btn-primary btn-sm' %>
    </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>ブログを作成する</h2>
        <%= render 'form' %>
    </div>
</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
    <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <div class="blog-text">
            <p class="left"><strong>タイトル</strong></p>
            <p class="left"><%= @blog.title %></p>
            <p class="left"><strong>内容</strong></p>
            <p class="left"><%= @blog.content %></p>
            <p class="right">
            投稿者: <%= link_to "#{@blog.user.name}", user_path(@blog.user) %><br>
            作成時間: <%= localize(@blog.created_at, format: :default) %>
            </p>
        </div>
        <p>コメント一覧</p>
        <div id="comments_area" >
            <%= render 'comments/index', comments: @comments, blog: @blog %>
        </div>
        <%= render 'comments/form', comment: @comment, blog: @blog %>
        <% if current_user.id == @blog.user_id %>
            <%= link_to '編集', edit_blog_path(@blog) %> |
        <% end %>
        <%= link_to '戻る', blogs_path %>
    </div>
</div>