config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :notifications, only: [:index]
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  post 'contacts/new' => 'contacts#new'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :charge, class_name: 'User', foreign_key: 'charge_id'
  has_many :submit_requests, dependent: :destroy
  validates :title, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(user_id: params[:user_id]).where.not(done: true).order(updated_at: :desc)
    @user = User.find(params[:user_id])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new(user_id: params[:user_id], charge_id: params[:user_id])
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to user_tasks_url, notice: 'タスクを登録しました。' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to user_tasks_url, notice: 'タスクを編集しました。' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'タスクを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :title, :content, :deadline, :charge_id, :done, :status)
    end

    def correct_user
      @user = User.find(params[:user_id])
      redirect_to(user_tasks_path(current_user)) unless current_user == @user
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@task.user, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :charge_id %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, size: '50*20', class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.select :status, [["未着手", "0"], ["対応中", "1"]], class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit '決定', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h1>タスク編集</h1>
    <%= render 'form' %>
    <%= link_to '詳細', user_task_path(@task.user, @task), class: 'btn btn-default' %> |
    <%= link_to '戻る', user_tasks_path(@task.user), class: 'btn btn-default' %>
</div>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= link_to '新規作成', new_user_task_path(@user), class: 'btn btn-default' %>
<br>
<br>
<div class="task col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>ユーザー</th>
                <th>タイトル</th>
                <th>内容</th>
                <th>締め切り</th>
                <th>担当者</th>
                <th>Done</th>
                <th>ステータス</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @tasks.each do |task| %>
                <tr>
                    <td><%= task.user.name %></td>
                    <td><%= task.title %></td>
                    <td><%= task.content %></td>
                    <td><%= task.deadline.strftime("%Y/%m/%d %R") %></td>
                    <td><%= task.charge.name %></td>
                    <td><%= if task.done? then "完了" else "未完了" end %></td>
                    <td><%= task.status == 1? "対応中" : "未着手" %></td>
                    <td><%= link_to '詳細', user_task_path(task.user, task), class: 'btn btn-info' %></td>
                    <td><%= link_to '編集', edit_user_task_path(task.user, task), class: 'btn btn-success' %></td>
                    <td><%= link_to '削除', user_task_path(task.user, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <br>
</div>

app/views/tasks/new.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h1>新規タスク作成</h1>
    <%= render 'form' %>
    <%= link_to '戻る', user_tasks_path(@task.user_id), class: 'btn btn-default' %>
</div>

app/views/tasks/show.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="left">
        <p>
        <h3>ユーザー:</h3>
        <%= @task.user.name %> (<%= @task.user.email %>)
        </p>

        <p>
        <h3>タイトル:</h3>
        <%= @task.title %>
        </p>

        <p>
        <h3>内容:</h3>
        <%= @task.content %>
        </p>

        <p>
        <h3>締め切り:</h3>
        <%= @task.deadline.strftime("%Y/%m/%d %R") %>
        </p>

        <p>
        <h3>依頼人:</h3>
        <%= @task.charge.name %>
        </p>

        <p>
        <h3>完了ステータス:</h3>
        <%= if @task.done? then "完了" else "未完了" end %>
        </p>

        <p>
        <h3>状態:</h3>
        <%= @task.status == 1? "対応中" : "未着手" %>
        </p>
    </div>
    <%= link_to '編集', edit_user_task_path(@task.user, @task), class: 'btn btn-default' %> |
    <%= link_to '戻る', user_tasks_path(@task.user), class: 'btn btn-default' %>
</div>