config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :notifications, only: [:index]
    resources :submit_requests, shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  post 'contacts/new' => 'contacts#new'

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :charger, class_name: 'User', foreign_key: 'charge_id'
end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy]
  before_action :submit_params, only: [:approve, :unapprove, :reject]

  def index
    @submit_requests = SubmitRequest.where(user_id: current_user.id).order(updated_at: :desc)
    @tasks = Task.where(user_id: params[:user_id]).where.not(done: true, status: 1).order(updated_at: :desc)
    @user = User.find(params[:user_id])
  end

  def new
    # 相互フォローユーザー
    @users = current_user.friend
    # 自分が作成した未完了タスク
    @tasks = current_user.tasks.where(done: false)
    # フォーム送信用に取得
    @user = current_user
    # リクエスト新規作成用
    @submit_request = current_user.submit_requests.build(status: 1)
  end

  def create
    @submit_request = SubmitRequest.new(submit_request_params)
    respond_to do |format|
      if @submit_request.save
        @submit_request.task.update(status: 1)
        format.html { redirect_to user_submit_requests_path(current_user.id, @submit_request), notice: '依頼を送信しました。' }
        format.json { render :show, status: :created, location: @submit_request }
      else
        format.html { render :new }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
    # 相互フォローユーザー
    @users = current_user.friend
    # 自分が作成した未完了タスク
    @tasks = current_user.tasks.where(done: false)
  end

  def update
    respond_to do |format|
      if @submit_request.update(submit_request_params)
        @submit_request.task.update(charge_id: submit_request_params[:charge_id])
        format.html { redirect_to user_submit_requests_path(current_user.id, @submit_request), notice: '依頼を編集しました。'}
        format.json { render :show, status: :ok, location: @submit_request }
      else
        format.html { render :edit }
        format.json { render json: @submit_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  def approve
    @submit_request.update(status: 2)
    @submit_request.task.update(status: 2)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
    respond_to do |format|
      format.js { render :reaction_inbox }
    end
  end

  def unapprove
    @submit_request.update(status: 9)
    @submit_request.task.update(status: 9, charge_id: @submit_request.user_id)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
    respond_to do |format|
      format.js { render :reaction_inbox }
    end
  end

  def reject
    @submit_request.update(status: 8)
    @submit_request.task.update(status: 8, charge_id: current_user.id)
    @submit_requests = SubmitRequest.where(user_id: current_user.id).order(updated_at: :desc)
    respond_to do |format|
      format.js { render :reaction_inbox }
    end
  end

  def inbox
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
  end

  private
    def submit_request_params
      params.require(:submit_request).permit(:task_id, :user_id, :charge_id, :status, :message)
    end

    def set_submit_request
      @submit_request = SubmitRequest.find(params[:id])
    end

    def submit_params
      @submit_request = SubmitRequest.find(params[:submit_request_id].to_i)
    end
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
  def status_display_name(status)
    case status
    when 1
      '未承認'
    when 2
      '承認済み'
    when 8
      '取消済み'
    when 9
      '却下'
    end
  end

  def done_display_name(done)
    done ? '完了' : '未完了'
  end
end

app/views/submit_requests/_form.html.erb
<%= form_for([@user, @submit_request]) do |f| %>
    <p><%= f.collection_select :task_id, @tasks, :id, :title, {}, class: "form-control title" %></p>
    <p><%= f.collection_select :charge_id, @users, :id, :name, {}, class: "form-control" %></p>
    <p><%= f.text_area :message, placeholder: "依頼メッセージ", size: "50*20", class: "form-control" %></p>
    <%= f.hidden_field :user_id  %>
    <%= f.hidden_field :status %>
    <div class="button-panel row">
        <p><%= f.submit "依頼する", class: "button col-xs-12" %></p>
    </div>
<% end %>
<%= link_to '戻る', user_submit_requests_path(current_user), class: 'btn btn-default' %>

app/views/submit_requests/_submit_requests_list.html.erb
<% if @submit_requests.present? %>
    <div class="task col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>登録者</th>
                    <th>タイトル</th>
                    <th>担当者</th>
                    <th>依頼日</th>
                    <th>締め切り</th>
                    <th>ステータス</th>
                    <th>状況</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% submit_requests.each do |submit_request| %>
                    <tr>
                        <td><%= submit_request.user.name if  submit_request.user.present? %></td>
                        <td><%= submit_request.task.title %></td>
                        <% if submit_request.charge_id == current_user.id %>
                            <td>(自分)</td>
                        <% else %>
                            <td><%= submit_request.charger.name %></td>
                        <% end %>
                        <td><%= submit_request.created_at.strftime("%Y/%m/%d %R") %></td>
                        <td><%= submit_request.task.deadline.strftime("%Y/%m/%d %R") %></td>
                        <td><%= status_display_name(submit_request.status) %></td>
                        <td><%= done_display_name(submit_request.task.done) %></td>
                        <td data-featherlight="#<%= (submit_request.id) %>"><%= link_to 'メッセージ', submit_request_path(submit_request), class: 'btn btn-primary' %></td>
                        <% if submit_request.charge_id == current_user.id %>
                            <td>
                                <%= link_to '承認', submit_request_approve_path(submit_request), remote: true, class: 'btn btn-success' %>
                                <%= link_to '却下', submit_request_unapprove_path(submit_request), remote: true, class: 'btn btn-danger' %>
                            </td>
                        <% end %>
                        <% if submit_request.user_id == current_user.id %>
                            <td>
                                <%= link_to '依頼を却下する', submit_request_reject_path(submit_request), data: submit_request.id, remote: true, class: 'btn btn-warning' if submit_request.status == 1 %>
                                <%= link_to '編集', edit_submit_request_path(submit_request), class: 'btn btn-info' %>
                                <%= link_to '削除', submit_request_path(submit_request), method: :delete, remote: true, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
                            </td>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
<% end %>

app/views/submit_requests/edit.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>依頼編集</h2>
    <%= render 'form' %>
</div>

app/views/submit_requests/inbox.html.erb
<h1>依頼されているタスク一覧</h1>
<div class="container">
    <br>
    <%= link_to '依頼一覧に戻る', user_submit_requests_path, class: 'btn btn-default' %>
    <br>
    <br>
    <div class="inbox_list_<%= current_user.id %>" id="inbox_list_<%= current_user.id %>">
        <%= render 'submit_requests_list', submit_requests: @submit_requests %>
    </div>
</div>

app/views/submit_requests/index.html.erb
<h1>依頼一覧</h1>
<div class="conttainer">
    <br>
    <p>
    <%= link_to '新規依頼', new_user_submit_request_path, class: 'btn btn-default' %>
    <%= link_to '依頼されているタスク一覧', inbox_user_submit_requests_path, class: 'btn btn-default' %>
    </p>
    <div id="submit_requests_<%= current_user.id %>">
        <%= render 'submit_requests_list', submit_requests: @submit_requests %>
    </div>
</div>

app/views/submit_requests/new.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div>
        <h2>依頼する内容</h2>
        <div>
            <% if @users.blank? %>
                依頼するユーザーがいません。
            <% elsif current_user.tasks.present? %>
                <%= render 'form' %>
            <% else %>
                依頼できるものがありません。
            <% end %>
        </div>
    </div>
</div>

app/views/submit_requests/reaction_inbox.js.erb
$("#inbox_list_<%= current_user.id %>").html("<%= j(render 'submit_requests_list', submit_requests: @submit_requests) %>");
$("#submit_requests_<%= current_user.id %>").html("<%= j(render 'submit_requests_list', submit_requests: @submit_requests) %>");

app/views/submit_requests/show.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="left">

        <p>
        <h3>依頼人:</h3>
        <% if @submit_request.charge_id == current_user.id %>
            <td>(自分)</td>
        <% else %>
            <td><%= @submit_request.charger.name %></td>
        <% end %>
        </p>

        <p>
        作成日：<%= @submit_request.created_at.strftime("%Y/%m/%d %R") %>
        </p>

        <p>
        <h3>タイトル:</h3>
        <%= @submit_request.task.title %>
        </p>

        <p>
        <h3>メッセージ:</h3>
        <%= @submit_request.message %>
        </p>

        <p>
        <h3>締め切り:</h3>
        <%= @submit_request.task.deadline.strftime("%Y/%m/%d %R") %>
        </p>

        <p>
        <h3>依頼人:</h3>
        <%= @submit_request.charger.name %>
        </p>

        <p>
        <h3>完了ステータス:</h3>
        <%= done_display_name(@submit_request.task.done) %>
        </p>

        <p>
        <h3>状態:</h3>
        <%= status_display_name(@submit_request.status) %>
        </p>
    </div>

<%= link_to '戻る', user_submit_requests_path(current_user), class: 'btn btn-default' %>
</div>